language: python
env:
  global:
    - secure: hiQzgKWkbw9FvIGIyz3f7xaDlZruOQdMIB+LfVNokKp5wOnB4q7VIElOgPS/2wbflnssdQP5tM0rhGtsfeQ/bfi1V9q8sT4f88xTuPFrr0mvZcytKcBzurWf0qfKA01A5QMVohk3g7Uy/I5uGda29wdKvOPmgOjtzu0jWYxxKL2c8U1nPZ6xdb84Ld3eoq8V8nfTMAF1MpFGzmrTfINYPYYArF8X9sPRRS/PlYmx7tM7Zh5XnaqwUzmBie0WaYDG94H7gPqN82h+R1gkZfsWqIzD7A0v1dIqTwO+wwdGcJO10PeZsueI1II1TyrMKWKSZJXL8Zf3WI8gyrqE4GArP3wWlFHmsWFwHTFsQV70k9fD8R1FN/CI1PTp8vn6VpyGclkFXpVwOICN9qDurHxaF4OcvovkzKV6CrHNu6HhPjWdtmRU3iYLJ6dcFaP/6mk7KTxNbSAl0QoArzLPeieVOd7Ka4gN8fyPQjpHwW1g7gvAOhTD9EPcC4QDNeCdJop/sdLpkf1PLiiy2yDrkcUntPCVpT+OfvDrgWIfzeqllr2aHvzLwU+Z6P1l3qFxNday2Bb6zq6QzUgLmSfbaKz5Tt+frbFUhdRrsUPJd/FsZNR3PRpEYfe2ZPH4LXBscuGk5ofAwbBRoda9ztaOL1ZW4tXuWzHrii6g9ayRsL7hjNA=
install:
  - pip install GitPython
  - export TRAVIS_COMMIT_MSG="$TRAVIS_REPO_SLUG - $(git log --format=%B --no-merges -n 1)"
  - git clone https://github.com/xbmc-catchuptv-au/repo-devel.git .deploy
script:
  - cd .deploy
  - "./manage_repo.py ../"
after_script:
  - git config --global user.email 'aussieaddons@aussieaddons.com'
  - git config --global user.name 'Aussie Add-ons Bot'
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add .
  - git commit --allow-empty -m "$TRAVIS_COMMIT_MSG"
  - git push
